### ISSUE TITLE
Prism Launcher has a themes repo

### ISSUE THREAD

**Issue by AshtakaOOf** [Lylythii/PrismThemes#1]
Came across this repo by accident. 
So if you want to, you can submit your themes to our themes repo.
I will make sure to add it to the website if you do :)

https://github.com/PrismLauncher/Themes
https://prismlauncher.org/wiki/help-pages/change-themes/

**Comment by Lylythii** [comment]
Hii! I meant to check this out last night, but something came up.

I'll look into submitting a PR sometime soon.
Additionally, I checked the Prism website & noticed there's an existing "Nord" theme. Not sure if I should discard my existing one as a result.

Either way, happy to contribute.

**Comment by Lylythii** [comment]
PR opened on PrismLauncher themes repo; https://github.com/PrismLauncher/Themes/pull/10

Thanks again for letting me know!
